/**
 * Command type enum
 * @enum {String}
 */
export default {
    MOVE_COMMAND: 'MOVE_COMMAND',
    ATTACK_COMMAND: 'ATTACK_COMMAND',
    LOOT_COMMAND: 'LOOT_COMMAND',
    END_ACTION_COMMAND: 'END_ACTION_COMMAND',
    END_TURN_COMMAND: 'END_TURN_COMMAND',
};
