/**
 * Event types
 * @enum {String}
 */
export default {
    MOVE_EVENT: 'MOVE_EVENT',
    ATTACK_EVENT: 'ATTACK_EVENT',
    DEFEND_EVENT: 'DEFEND_EVENT',
    LOG_EVENT: 'LOG_EVENT',
    LOOT_EVENT: 'LOOT_EVENT',
    END_ACTION_EVENT: 'END_ACTION_EVENT',
    ATTRIBUTE_CHANGE_EVENT: 'ATTRIBUTE_CHANGE_EVENT',
    ACTOR_KILLED_EVENT: 'ACTOR_KILLED_EVENT',
    START_TURN_EVENT: 'START_TURN_EVENT',
    END_TURN_EVENT: 'END_TURN_EVENT',
    DAMAGE_EVENT: 'DAMAGE_EVENT',
    ITEM_EQUIPPED_EVENT: 'ITEM_EQUIPPED_EVENT',
    ITEM_DROPPED_EVENT: 'ITEM_DROPPED_EVENT',
};
